apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: calendar
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2NhbGVuZGFyOnBhc3N3b3JkMTIzQGRiL2NhbGVuZGFy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-api
  namespace: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-api
  template:
    metadata:
      labels:
        app: calendar-api
    spec:
      containers:
      - name: calendar-api
        image: calendar-api-image
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: "CalendarService"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-api-service
  namespace: calendar
spec:
  selector:
    app: calendar-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calendar-api-ingress
  namespace: calendar
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - http:
      paths:
      - path: /calendar
        pathType: Prefix
        backend:
          service:
            name: calendar-api-service
            port:
              number: 80

