version: '3.8'
services:
  calendar_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=CalendarService
      - DATABASE_URL=postgresql://calendar:password123@db/calendar
    depends_on:
      - db
    networks:
      - calendar_net

  db:
    image: postgres:13-alpine
    env_file:
      - database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calendar_net

networks:
  calendar_net:

volumes:
  postgres_data:
